// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.GPIMSModels;

[Table("A_APA_MC_6")]
public partial class A_APA_MC_6
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    public string CCERUpload_2022_2023 { get; set; }

    [Required]
    public string CCERUpload_2023_2024 { get; set; }

    [Required]
    public string OSRDataUpload { get; set; }

    [Required]
    public string CCERUpload_2022_2023_path { get; set; }

    [Required]
    public string CCERUpload_2023_2024_path { get; set; }

    [Required]
    public string OSRDataUpload_path { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalTaxinINR_2223 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalNonTaxinINR_2223 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalOSRinINR_2223 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OSRDeductionAmountinINR_2223 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalTaxinINR_2324 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalNonTaxinINR_2324 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalOSRinINR_2324 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OSRDeductionAmountinINR_2324 { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}