// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.GPIMSModels;

[Table("mst_UserMaster")]
public partial class mst_UserMaster
{
    public long id { get; set; }

    [Key]
    [StringLength(20)]
    public string UserName { get; set; }

    public long AccessID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string UserPassword { get; set; }

    public long RoleCode { get; set; }

    [StringLength(20)]
    public string MobileNo { get; set; }

    public long LoginStatus { get; set; }

    public int CurrentLoginStatus { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LoginTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LogOutTime { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [ForeignKey("RoleCode")]
    [InverseProperty("mst_UserMasters")]
    public virtual mst_UserRole RoleCodeNavigation { get; set; }
}