// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using APATools.Models;
using Microsoft.EntityFrameworkCore;

namespace APATools.Context;

public partial class APAToolsContext : DbContext
{
    public APAToolsContext(DbContextOptions<APAToolsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<A_APA_ALL_Remark> A_APA_ALL_Remarks { get; set; }

    public virtual DbSet<A_APA_Completed_Count> A_APA_Completed_Counts { get; set; }

    public virtual DbSet<A_APA_District_AllowCheck> A_APA_District_AllowChecks { get; set; }

    public virtual DbSet<A_APA_MC_1> A_APA_MC_1s { get; set; }

    public virtual DbSet<A_APA_MC_2> A_APA_MC_2s { get; set; }

    public virtual DbSet<A_APA_MC_3> A_APA_MC_3s { get; set; }

    public virtual DbSet<A_APA_MC_4> A_APA_MC_4s { get; set; }

    public virtual DbSet<A_APA_MC_5> A_APA_MC_5s { get; set; }

    public virtual DbSet<A_APA_MC_6> A_APA_MC_6s { get; set; }

    public virtual DbSet<A_APA_TE_1> A_APA_TE_1s { get; set; }

    public virtual DbSet<A_APA_TE_10> A_APA_TE_10s { get; set; }

    public virtual DbSet<A_APA_TE_11> A_APA_TE_11s { get; set; }

    public virtual DbSet<A_APA_TE_13> A_APA_TE_13s { get; set; }

    public virtual DbSet<A_APA_TE_14> A_APA_TE_14s { get; set; }

    public virtual DbSet<A_APA_TE_16> A_APA_TE_16s { get; set; }

    public virtual DbSet<A_APA_TE_17> A_APA_TE_17s { get; set; }

    public virtual DbSet<A_APA_TE_18> A_APA_TE_18s { get; set; }

    public virtual DbSet<A_APA_TE_18_HWH> A_APA_TE_18_HWHs { get; set; }

    public virtual DbSet<A_APA_TE_19> A_APA_TE_19s { get; set; }

    public virtual DbSet<A_APA_TE_2> A_APA_TE_2s { get; set; }

    public virtual DbSet<A_APA_TE_20> A_APA_TE_20s { get; set; }

    public virtual DbSet<A_APA_TE_3> A_APA_TE_3s { get; set; }

    public virtual DbSet<A_APA_TE_4> A_APA_TE_4s { get; set; }

    public virtual DbSet<A_APA_TE_5> A_APA_TE_5s { get; set; }

    public virtual DbSet<A_APA_TE_6> A_APA_TE_6s { get; set; }

    public virtual DbSet<A_APA_TE_7> A_APA_TE_7s { get; set; }

    public virtual DbSet<A_APA_TE_8> A_APA_TE_8s { get; set; }

    public virtual DbSet<A_APA_TE_9> A_APA_TE_9s { get; set; }

    public virtual DbSet<mst_FinancialYear> mst_FinancialYears { get; set; }

    public virtual DbSet<mst_LocationBlock> mst_LocationBlocks { get; set; }

    public virtual DbSet<mst_LocationDistrict> mst_LocationDistricts { get; set; }

    public virtual DbSet<mst_LocationGP> mst_LocationGPs { get; set; }

    public virtual DbSet<mst_LocationState> mst_LocationStates { get; set; }

    public virtual DbSet<mst_LocationSubDivision> mst_LocationSubDivisions { get; set; }

    public virtual DbSet<mst_UserMaster> mst_UserMasters { get; set; }

    public virtual DbSet<mst_UserPassword> mst_UserPasswords { get; set; }

    public virtual DbSet<mst_UserRole> mst_UserRoles { get; set; }

    public virtual DbSet<view_alllocation> view_alllocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<A_APA_ALL_Remark>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        modelBuilder.Entity<A_APA_Completed_Count>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        modelBuilder.Entity<A_APA_MC_1>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_A_APA_C1");
        });

        modelBuilder.Entity<A_APA_MC_5>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_A_APA_MC_5_TE_11");
        });

        modelBuilder.Entity<A_APA_TE_20>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__A_APA_TE__3214EC2746D5C7A2");
        });

        modelBuilder.Entity<mst_FinancialYear>(entity =>
        {
            entity.HasKey(e => e.FYCode).HasName("PK__mst_Fina__4B7AA11F30C3C713");

            entity.Property(e => e.FYCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<mst_LocationBlock>(entity =>
        {
            entity.HasKey(e => e.BlockCode).HasName("PK__mst_Loca__A022B7D656E2D326");

            entity.Property(e => e.BlockCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.DistrictCodeNavigation).WithMany(p => p.mst_LocationBlocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_Locat__Distr__6477ECF3");

            entity.HasOne(d => d.SubDivisionCodeNavigation).WithMany(p => p.mst_LocationBlocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_Locat__SubDi__6383C8BA");
        });

        modelBuilder.Entity<mst_LocationDistrict>(entity =>
        {
            entity.HasKey(e => e.DistrictCode).HasName("PK__mst_Loca__3D4E86AA24D38039");

            entity.Property(e => e.DistrictCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.StateCodeNavigation).WithMany(p => p.mst_LocationDistricts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_Locat__State__5DCAEF64");
        });

        modelBuilder.Entity<mst_LocationGP>(entity =>
        {
            entity.HasKey(e => e.GPCode).HasName("PK__mst_Loca__D298147494DCD7E8");

            entity.Property(e => e.GPCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.BlockCodeNavigation).WithMany(p => p.mst_LocationGPs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_Locat__Block__09A971A2");
        });

        modelBuilder.Entity<mst_LocationState>(entity =>
        {
            entity.HasKey(e => e.StateCode).HasName("PK__mst_Loca__D515E98B68B2A217");

            entity.Property(e => e.StateCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<mst_LocationSubDivision>(entity =>
        {
            entity.HasKey(e => e.SubDivisionCode).HasName("PK__mst_Loca__4784F40A6ABED362");

            entity.Property(e => e.SubDivisionCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.DistrictCodeNavigation).WithMany(p => p.mst_LocationSubDivisions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_Locat__Distr__60A75C0F");
        });

        modelBuilder.Entity<mst_UserMaster>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__mst_User__C9F28457A15FA284");

            entity.Property(e => e.MobileNo).IsFixedLength();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.mst_UserMasters)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_UserM__RoleC__0C85DE4D");
        });

        modelBuilder.Entity<mst_UserPassword>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__mst_User__C9F2845771F5D82F");

            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<mst_UserRole>(entity =>
        {
            entity.HasKey(e => e.RoleCode).HasName("PK__mst_User__D62CB59DB952FF8F");

            entity.Property(e => e.RoleCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<view_alllocation>(entity =>
        {
            entity.ToView("view_alllocation");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}