// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APATools.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace APATools.Context
{
    public partial interface IAPAToolsContextProcedures
    {
        Task<List<____Sp_APA_Checked_Complete_GPResult>> ____Sp_APA_Checked_Complete_GPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_Checked_Complete_GPResult>> Sp_APA_Checked_Complete_GPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_GetAllMC_TE_ResultsResult>> Sp_APA_GetAllMC_TE_ResultsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_GetAllMC_TE_Results_with_ValuesResult>> Sp_APA_GetAllMC_TE_Results_with_ValuesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_List_Allowed_District_at_PMUResult>> Sp_APA_List_Allowed_District_at_PMUAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_Update_CountResult>> Sp_APA_Update_CountAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_Update_Count_BlockwiseResult>> Sp_APA_Update_Count_BlockwiseAsync(long? districtCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_APA_Update_Count_by_GPResult>> Sp_APA_Update_Count_by_GPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Sp_Edit_Remove_From_GP_for_APAAsync(long? districtCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Sp_Edit_Update_From_GP_for_APAAsync(string tableName, long? districtCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_UserLoginResult>> Sp_UserLoginAsync(string user_Id, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
