// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using APATools.GPIMSModels;
using Microsoft.EntityFrameworkCore;

namespace APATools.OldContext;

public partial class GPIMSContext : DbContext
{
    public GPIMSContext(DbContextOptions<GPIMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<A_APA_MC_6> A_APA_MC_6_olds { get; set; }

    public virtual DbSet<mst_UserMaster> mst_UserMasters { get; set; }

    public virtual DbSet<mst_UserPassword> mst_UserPasswords { get; set; }

    public virtual DbSet<mst_UserRole> mst_UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<mst_UserMaster>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__mst_User__C9F28457A15FA284");

            entity.Property(e => e.MobileNo).IsFixedLength();
            entity.Property(e => e.id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.mst_UserMasters)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__mst_UserM__RoleC__0C85DE4D");
        });

        modelBuilder.Entity<mst_UserPassword>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__mst_User__C9F28457522C4359");

            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<mst_UserRole>(entity =>
        {
            entity.HasKey(e => e.RoleCode).HasName("PK__mst_User__D62CB59D9EF0D850");

            entity.Property(e => e.RoleCode).ValueGeneratedNever();
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}