// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_16")]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814752ED2D393", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814754FDD5785", IsUnique = true)]
public partial class A_APA_TE_16
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OSR_Collected_202425 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OSR_Utilized_Development { get; set; }

    [Required]
    public string Upload_Annex_7 { get; set; }

    [Required]
    public string Upload_Annex_7_Path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}