// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_19")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475389465FA", IsUnique = true)]
public partial class A_APA_TE_19
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ExpenditureforSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ExpenditureforCFCUntied { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ExpenditureforOSR { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal UntiedAmountSpentfromCFCSFCOSR202425 { get; set; }

    [Required]
    public string UploadAnnex8_PDF { get; set; }

    [Required]
    public string UploadAnnex8_PDF_path { get; set; }

    [Required]
    public string UploadAnnex8_Excel { get; set; }

    [Required]
    public string UploadAnnex8_Excel_path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}