// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_5")]
[Index("GPCode", Name = "UQ__A_APA_TE__D298147511C11EA5", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814754A034BE9", IsUnique = true)]
public partial class A_APA_TE_5
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_1 { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_1 { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_DPR { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_DPR_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_2 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_2 { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_2 { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_DPR { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_DPR_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_3 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_3 { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_3 { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_DPR { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_DPR_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_4 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_4 { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_4 { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_DPR { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_DPR_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_5 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_5 { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_5 { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_DPR { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_DPR_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate_Path { get; set; }

    public int ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}