// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_MC_1")]
[Index("GPCode", Name = "UQ__A_APA_MC__D2981475B6BF6EA5", IsUnique = true)]
public partial class A_APA_MC_1
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalNoofMember { get; set; }

    public long NoofMemberAttended { get; set; }

    [Required]
    [Unicode(false)]
    public string EvidenceofPlanApprovalResolution { get; set; }

    [Required]
    [Unicode(false)]
    public string EvidenceofPlanApprovalResolution_path { get; set; }

    [Required]
    [Unicode(false)]
    public string TotalMembersDeclaration_pdf { get; set; }

    [Required]
    [Unicode(false)]
    public string TotalMembersDeclaration_pdf_path { get; set; }

    [Required]
    [Unicode(false)]
    public string TotalMembersDeclaration_excel { get; set; }

    [Required]
    [Unicode(false)]
    public string TotalMembersDeclaration_excel_path { get; set; }

    [Column(TypeName = "date")]
    public DateTime PlanApprovalDate { get; set; }

    [Required]
    [StringLength(50)]
    public string SingleAgendaMeeting { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }

    public int ActiveStatus { get; set; }
}