// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_8")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475B02C6DD6", IsUnique = true)]
public partial class A_APA_TE_8
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalNoofWTDone { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_WT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_WT_Path { get; set; }

    public int ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}