// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_10")]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814755FF40AAA", IsUnique = true)]
public partial class A_APA_TE_10
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Column(TypeName = "date")]
    public DateOnly GBMeetingDate { get; set; }

    [Required]
    [StringLength(50)]
    public string Form27Approved { get; set; }

    [Required]
    public string ResolutionDoconForm27 { get; set; }

    [Required]
    public string ResolutionDoconForm27_path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}