// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_MC_2")]
[Index("GPCode", Name = "UQ__A_APA_MC__D2981475751DD247", IsUnique = true)]
public partial class A_APA_MC_2
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long NoofPhysicallyCompletedActivities { get; set; }

    public long NoofIssuedWorkOrder { get; set; }

    [Required]
    public string DeclarationStatusPhysicalCompletedActivities { get; set; }

    [Required]
    public string DeclarationStatusPhysicalCompletedActivities_Path { get; set; }

    [Required]
    public string DeclarationPlan_Implementation { get; set; }

    [Required]
    public string DeclarationPlan_Implementation_Path { get; set; }

    [Required]
    public string EvidenceofCompletedActivity { get; set; }

    [Required]
    public string EvidenceofCompletedActivity_Path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}