// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
[Table("A_APA_MC_3")]
public partial class A_APA_MC_3
{
    public double? LGDCODE { get; set; }

    public long? GPCode { get; set; }

    [StringLength(255)]
    public string FYName { get; set; }

    [StringLength(255)]
    public string DISTRICT { get; set; }

    [StringLength(255)]
    public string BLOCK { get; set; }

    [StringLength(255)]
    public string GP { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? OB_CFC { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? OB_SFC { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? OB_OSR { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RECPT_CFC_UPTO_DEC_2024 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RECPT_SFC_UPTO_DEC_2024 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RECPT_OSR_UPTO_DEC_2024 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? EXP_CFC_UPTO_MAR_2025 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? EXP_SFC_UPTO_MAR_2025 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? EXP_OSR_UPTO_MAR_2025 { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Total_OB { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Total_Receipt { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Total_Expenditure { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Percentage { get; set; }

    [StringLength(255)]
    public string A_APA_MC_3_Result { get; set; }

    public long? FYCode { get; set; }
}