// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_4")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475009C7527", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475D3200F68", IsUnique = true)]
public partial class A_APA_TE_4
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalnoofActivitiesofGramSabha { get; set; }

    public long TotalnoofActivitiesRecomendedByGramSabha { get; set; }

    [Required]
    public string GramSavaMeetingResolution { get; set; }

    [Required]
    public string GramSavaMeetingResolution_Path { get; set; }

    [Required]
    public string DeclarationofAnnex6 { get; set; }

    [Required]
    public string DeclarationofAnnex6_path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}