// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_1")]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814756376B8F1", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475F027ACB7", IsUnique = true)]
public partial class A_APA_TE_1
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalNoofPlanActivities { get; set; }

    public long TotalNoofPlanUnderSankalpa { get; set; }

    [Required]
    public string PlanActivitiesUploadForPDF { get; set; }

    [Required]
    public string PlanActivitiesUploadForPDF_Path { get; set; }

    [Required]
    public string PlanActivitiesUploadForExcel { get; set; }

    [Required]
    public string PlanActivitiesUploadForExcel_Path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}