// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_MC_5")]
[Index("GPCode", Name = "UQ__A_APA_MC__D2981475955CEBB6", IsUnique = true)]
public partial class A_APA_MC_5
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    [StringLength(50)]
    public string AuditOpinion { get; set; }

    [Required]
    [StringLength(50)]
    public string AuditCertificate { get; set; }

    [Required]
    public string AuditCertificate_Path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}