// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_3")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475CBD77A45", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475EF681256", IsUnique = true)]
public partial class A_APA_TE_3
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    public string MeetingResolutionUpload { get; set; }

    [Required]
    public string MeetingResolutionUpload_path { get; set; }

    [Required]
    public string GPDeclarationUpload { get; set; }

    [Required]
    public string GPDeclarationUpload_path { get; set; }

    public long TotalNoofMeetingsConducted { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}