// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
[Table("A_APA_TE_18_HWH")]
public partial class A_APA_TE_18_HWH
{
    public double GPCode { get; set; }

    [Column("System_on_ 2nd_ April_2025")]
    public double System_on__2nd__April_2025 { get; set; }
}