// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_6")]
[Index("GPCode", Name = "UQ__A_APA_TE__D298147563C37C50", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475E66CEF63", IsUnique = true)]
public partial class A_APA_TE_6
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_1_MT { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_2_MT { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_3_MT { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_4_MT { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_5_MT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_1_MT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_2_MT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_3_MT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_4_MT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_5_MT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_1_MT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_2_MT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_3_MT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_4_MT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_5_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_MT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate_MT { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate_MT_Path { get; set; }

    public int ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}