// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_14")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475870AB42E", IsUnique = true)]
public partial class A_APA_TE_14
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    public string Form7Upload { get; set; }

    [Required]
    public string Form7Upload_path { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Tax_non_tax_collected_ownsource_revenue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalOSRDemandCount { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}