// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_13")]
[Index("GPCode", Name = "UQ__A_APA_TE__D2981475094C57B2", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814752EE35C8E", IsUnique = true)]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814753A985330", IsUnique = true)]
public partial class A_APA_TE_13
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_1_CFCSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_1_CFCSFC { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_1_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_CFCSFC_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_2_CFCSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_2_CFCSFC { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_2_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_CFCSFC_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_3_CFCSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_3_CFCSFC { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_3_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_CFCSFC_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_4_CFCSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_4_CFCSFC { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_4_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_CFCSFC_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_5_CFCSFC { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_5_CFCSFC { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_5_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_CFCSFC_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_CFCSFC { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_CFCSFC_Path { get; set; }

    public int ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}