// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_Completed_Count")]
public partial class A_APA_Completed_Count
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long? MC_1 { get; set; }

    public long? MC_2 { get; set; }

    public long? MC_3 { get; set; }

    public long? MC_4 { get; set; }

    public long? MC_5 { get; set; }

    public long? MC_6 { get; set; }

    public long? TE_1 { get; set; }

    public long? TE_2 { get; set; }

    public long? TE_3 { get; set; }

    public long? TE_4 { get; set; }

    public long? TE_5 { get; set; }

    public long? TE_6 { get; set; }

    public long? TE_7 { get; set; }

    public long? TE_8 { get; set; }

    public long? TE_9 { get; set; }

    public long? TE_10 { get; set; }

    public long? TE_11 { get; set; }

    public long? TE_12 { get; set; }

    public long? TE_13 { get; set; }

    public long? TE_14 { get; set; }

    public long? TE_15 { get; set; }

    public long? TE_16 { get; set; }

    public long? TE_17 { get; set; }

    public long? TE_18 { get; set; }

    public long? TE_19 { get; set; }

    public long? TE_20 { get; set; }
}