// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_20")]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814757CAB24E0", IsUnique = true)]
public partial class A_APA_TE_20
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long GrievenceLogged { get; set; }

    public long GrievenceResolved { get; set; }

    [Required]
    [StringLength(50)]
    public string GrievenceImage { get; set; }

    [Required]
    public string GrievenceImage_Path { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }

    public int ActiveStatus { get; set; }
}