// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_9")]
[Index("GPCode", Name = "UQ__A_APA_TE__D29814754F9C096E", IsUnique = true)]
public partial class A_APA_TE_9
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalNoofActivitieshavingvaluesmorethanorequalstwolakh { get; set; }

    public long TotalNoofInspectedActivitiesmorethanorequalstwolakh { get; set; }

    [Required]
    public string WOActivityActivitieshavingvaluesmorethanorequalstwolakh { get; set; }

    [Required]
    public string WOActivityActivitieshavingvaluesmorethanorequalstwolakh_path { get; set; }

    [Required]
    public string InspectionReportActivitiesEstimate { get; set; }

    [Required]
    public string InspectionReportActivitiesEstimate_path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}