// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_District_AllowCheck")]
public partial class A_APA_District_AllowCheck
{
    [Key]
    public long ID { get; set; }

    public long? DistrictCode { get; set; }

    public long? AllowCheck { get; set; }
}