// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
[Table("A_APA_MC_4")]
public partial class A_APA_MC_4
{
    public double? LGDCODE { get; set; }

    public long? GPCode { get; set; }

    [StringLength(255)]
    public string DISTRICT { get; set; }

    [StringLength(255)]
    public string BLOCK { get; set; }

    [StringLength(255)]
    public string GP { get; set; }

    [StringLength(255)]
    public string FYName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? APR_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MAY_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JUN_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JUL_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AUG_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SEP_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OCT_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NOV_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DEC_2024 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? JAN_2025 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FEB_2025 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MAR_2025 { get; set; }

    public double? Total { get; set; }

    [StringLength(255)]
    public string A_APA_MC_4_Result { get; set; }

    public long? FYCode { get; set; }
}