// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_7")]
[Index("GPCode", Name = "UQ__A_APA_TE__D298147571F7D353", IsUnique = true)]
public partial class A_APA_TE_7
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_1_AQT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_1_AQT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_1_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_1_AQT_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_2_AQT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_2_AQT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_2_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_2_AQT_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_3_AQT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_3_AQT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_3_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_3_AQT_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_4_AQT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_4_AQT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_4_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_4_AQT_Path { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string ActivityName_5_AQT { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ActivityValue_5_AQT { get; set; }

    [Required]
    [StringLength(50)]
    public string FundofActivity_5_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string Activity_5_AQT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string EntireWOHightingAll_AQT_Path { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate_AQT { get; set; }

    [Required]
    [Unicode(false)]
    public string CompletionCertificate_AQT_Path { get; set; }

    public int ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}