// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("A_APA_TE_17")]
[Index("GPCode", Name = "UQ__A_APA_TE__D298147585543571", IsUnique = true)]
public partial class A_APA_TE_17
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    public long FYCode { get; set; }

    public long TotalMeetingConducted202425 { get; set; }

    [Required]
    public string UploadMeetingResolutionConducted202425 { get; set; }

    [Required]
    public string UploadMeetingResolutionConducted202425_Path { get; set; }

    public long ActiveStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string User_Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Entry_Time { get; set; }
}