// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

public partial class A_APA_ALL_Remark
{
    [Key]
    public long ID { get; set; }

    public long GPCode { get; set; }

    [Column(TypeName = "text")]
    public string MC_1 { get; set; }

    [Column(TypeName = "text")]
    public string MC_2 { get; set; }

    [Column(TypeName = "text")]
    public string MC_3 { get; set; }

    [Column(TypeName = "text")]
    public string MC_4 { get; set; }

    [Column(TypeName = "text")]
    public string MC_5 { get; set; }

    [Column(TypeName = "text")]
    public string MC_6 { get; set; }

    [Column(TypeName = "text")]
    public string TE_1 { get; set; }

    [Column(TypeName = "text")]
    public string TE_2 { get; set; }

    [Column(TypeName = "text")]
    public string TE_3 { get; set; }

    [Column(TypeName = "text")]
    public string TE_4 { get; set; }

    public long? TE_5 { get; set; }

    public long? TE_6 { get; set; }

    public long? TE_7 { get; set; }

    [Column(TypeName = "text")]
    public string TE_8 { get; set; }

    [Column(TypeName = "text")]
    public string TE_9 { get; set; }

    [Column(TypeName = "text")]
    public string TE_10 { get; set; }

    [Column(TypeName = "text")]
    public string TE_11 { get; set; }

    [Column(TypeName = "text")]
    public string TE_12 { get; set; }

    public long? TE_13 { get; set; }

    [Column(TypeName = "text")]
    public string TE_14 { get; set; }

    [Column(TypeName = "text")]
    public string TE_15 { get; set; }

    [Column(TypeName = "text")]
    public string TE_16 { get; set; }

    [Column(TypeName = "text")]
    public string TE_17 { get; set; }

    [Column(TypeName = "text")]
    public string TE_18 { get; set; }

    [Column(TypeName = "text")]
    public string TE_19 { get; set; }

    [Column(TypeName = "text")]
    public string TE_20 { get; set; }
}