// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
[Table("MC3_Update")]
public partial class MC3_Update
{
    public double? LGDCODE { get; set; }

    public double GPCode { get; set; }

    [StringLength(255)]
    public string FYName { get; set; }

    [StringLength(255)]
    public string DISTRICT { get; set; }

    [StringLength(255)]
    public string BLOCK { get; set; }

    [StringLength(255)]
    public string GP { get; set; }

    public double? OB_CFC { get; set; }

    public double? OB_SFC { get; set; }

    public double? OB_OSR { get; set; }

    public double? RECPT_CFC_UPTO_DEC_2024 { get; set; }

    public double? RECPT_SFC_UPTO_DEC_2024 { get; set; }

    public double? RECPT_OSR_UPTO_DEC_2024 { get; set; }

    public double? EXP_CFC_UPTO_MAR_2025 { get; set; }

    public double? EXP_SFC_UPTO_MAR_2025 { get; set; }

    public double? EXP_OSR_UPTO_MAR_2025 { get; set; }

    public double? Total_OB { get; set; }

    public double? Total_Receipt { get; set; }

    public double? Total_Expenditure { get; set; }

    public double? Percentage { get; set; }

    [StringLength(255)]
    public string A_APA_MC_3_Result { get; set; }

    public double? FYCode { get; set; }
}