// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
[Table("MC_Update_latest")]
public partial class MC_Update_latest
{
    public double ID { get; set; }

    public double GPCode { get; set; }

    public double FYCode { get; set; }

    public double OSRDeductionAmountinINR_2324 { get; set; }
}