// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_LocationDistrict")]
[Index("DistrictName", Name = "UQ__mst_Loca__F4708CA463BB880D", IsUnique = true)]
public partial class mst_LocationDistrict
{
    public long id { get; set; }

    [Key]
    public long DistrictCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string DistrictName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DistrictCodeGPMS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DistrictCodeOldMIS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DistrictCodeGIS { get; set; }

    public long StateCode { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(250)]
    public string Remarks { get; set; }

    [ForeignKey("StateCode")]
    [InverseProperty("mst_LocationDistricts")]
    public virtual mst_LocationState StateCodeNavigation { get; set; }

    [InverseProperty("DistrictCodeNavigation")]
    public virtual ICollection<mst_LocationBlock> mst_LocationBlocks { get; set; } = new List<mst_LocationBlock>();

    [InverseProperty("DistrictCodeNavigation")]
    public virtual ICollection<mst_LocationSubDivision> mst_LocationSubDivisions { get; set; } = new List<mst_LocationSubDivision>();
}