// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_FinancialYear")]
[Index("FYName", Name = "UQ__mst_Fina__F6F14CDEF1512792", IsUnique = true)]
public partial class mst_FinancialYear
{
    public long id { get; set; }

    [Key]
    public long FYCode { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string FYName { get; set; }

    public long ActiveForME1 { get; set; }

    public long ActiveForME2 { get; set; }

    public long ActiveForME3 { get; set; }

    public long ActiveForSansadProfile { get; set; }

    public long ActiveForDWS { get; set; }

    public long ActiveForPopulationVGDI { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }
}