// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_UserRole")]
[Index("RoleName", Name = "UQ__mst_User__8A2B61600FB05FE9", IsUnique = true)]
public partial class mst_UserRole
{
    public long id { get; set; }

    [Key]
    public long RoleCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleName { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [InverseProperty("RoleCodeNavigation")]
    public virtual ICollection<mst_UserMaster> mst_UserMasters { get; set; } = new List<mst_UserMaster>();
}