// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_LocationState")]
[Index("StateName", Name = "UQ__mst_Loca__55476315BFDF1A1B", IsUnique = true)]
public partial class mst_LocationState
{
    public long id { get; set; }

    [Key]
    public long StateCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string StateName { get; set; }

    public long StateCodeGPMS { get; set; }

    public long StateCodeOldMIS { get; set; }

    public long StateCodeGIS { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [InverseProperty("StateCodeNavigation")]
    public virtual ICollection<mst_LocationDistrict> mst_LocationDistricts { get; set; } = new List<mst_LocationDistrict>();
}