// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_LocationGP")]
public partial class mst_LocationGP
{
    public long id { get; set; }

    [Key]
    public long GPCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string GPName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string GPCodeGPMS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string GPCodeOldMIS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string GPCodeGIS { get; set; }

    public long BlockCode { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string GPCodeNEWGPMS { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [ForeignKey("BlockCode")]
    [InverseProperty("mst_LocationGPs")]
    public virtual mst_LocationBlock BlockCodeNavigation { get; set; }
}