// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_LocationBlock")]
public partial class mst_LocationBlock
{
    public long id { get; set; }

    [Key]
    public long BlockCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string BlockName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string BlockCodeGPMS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string BlockCodeOldMIS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string BlockCodeGIS { get; set; }

    public long SubDivisionCode { get; set; }

    public long DistrictCode { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [ForeignKey("DistrictCode")]
    [InverseProperty("mst_LocationBlocks")]
    public virtual mst_LocationDistrict DistrictCodeNavigation { get; set; }

    [ForeignKey("SubDivisionCode")]
    [InverseProperty("mst_LocationBlocks")]
    public virtual mst_LocationSubDivision SubDivisionCodeNavigation { get; set; }

    [InverseProperty("BlockCodeNavigation")]
    public virtual ICollection<mst_LocationGP> mst_LocationGPs { get; set; } = new List<mst_LocationGP>();
}