// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Table("mst_LocationSubDivision")]
public partial class mst_LocationSubDivision
{
    public long id { get; set; }

    [Key]
    public long SubDivisionCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string SubDivisionName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SubDivisionCodeGPMS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SubDivisionCodeOldMIS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SubDivisionCodeGIS { get; set; }

    public long DistrictCode { get; set; }

    public long ActiveStatus { get; set; }

    public long DeleteStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [ForeignKey("DistrictCode")]
    [InverseProperty("mst_LocationSubDivisions")]
    public virtual mst_LocationDistrict DistrictCodeNavigation { get; set; }

    [InverseProperty("SubDivisionCodeNavigation")]
    public virtual ICollection<mst_LocationBlock> mst_LocationBlocks { get; set; } = new List<mst_LocationBlock>();
}