// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APATools.Models
{
    public partial class Sp_APA_Update_Count_BlockwiseResult
    {
        [StringLength(250)]
        public string DistrictName { get; set; }
        public long DistrictCode { get; set; }
        [StringLength(250)]
        public string BlockName { get; set; }
        public long BlockCode { get; set; }
        [StringLength(250)]
        public string GPName { get; set; }
        public long GPCode { get; set; }
        public int? MC_1 { get; set; }
        public int? MC_2 { get; set; }
        public int? MC_5 { get; set; }
        public int? MC_6 { get; set; }
        public int? TE_1 { get; set; }
        public int? TE_2 { get; set; }
        public int? TE_3 { get; set; }
        public int? TE_4 { get; set; }
        public int? TE_5 { get; set; }
        public int? TE_6 { get; set; }
        public int? TE_7 { get; set; }
        public int? TE_8 { get; set; }
        public int? TE_9 { get; set; }
        public int? TE_10 { get; set; }
        public int? TE_11 { get; set; }
        public int? TE_13 { get; set; }
        public int? TE_14 { get; set; }
        public int? TE_16 { get; set; }
        public int? TE_17 { get; set; }
        public int? TE_18 { get; set; }
        public int? TE_19 { get; set; }
        public int? TE_20 { get; set; }
    }
}
