// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APATools.Models
{
    public partial class Sp_APA_List_Allowed_District_at_PMUResult
    {
        public long? DistrictCode { get; set; }
        [StringLength(250)]
        public string DistrictName { get; set; }
        public long? AllowCheck { get; set; }
    }
}
