// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APATools.Models
{
    public partial class Sp_APA_GetAllMC_TE_ResultsResult
    {
        public long DistrictCode { get; set; }
        [StringLength(250)]
        public string DistrictName { get; set; }
        [StringLength(250)]
        public string BlockName { get; set; }
        [StringLength(250)]
        public string GPName { get; set; }
        public long GPCode { get; set; }
        [StringLength(4)]
        public string MC1_Result { get; set; }
        [StringLength(4)]
        public string MC2_Result { get; set; }
        [StringLength(4)]
        public string MC3_Result { get; set; }
        [StringLength(4)]
        public string MC4_Result { get; set; }
        [StringLength(4)]
        public string MC5_Result { get; set; }
        [StringLength(4)]
        public string MC6_Result { get; set; }
        public int TE1_Result { get; set; }
        public int TE2_Result { get; set; }
        public int TE3_Result { get; set; }
        public int TE4_Result { get; set; }
        public int TE5_Result { get; set; }
        public int TE6_Result { get; set; }
        public int TE7_Result { get; set; }
        public int TE8_Result { get; set; }
        public int TE9_Result { get; set; }
        public int TE10_Result { get; set; }
        public int TE11_Result { get; set; }
        public int TE12_Result { get; set; }
        public int TE13_Result { get; set; }
        public int TE14_Result { get; set; }
        public int TE15_Result { get; set; }
        public int TE16_Result { get; set; }
        public int TE17_Result { get; set; }
        public int TE18_Result { get; set; }
        public int TE19_Result { get; set; }
        public int TE20_Result { get; set; }
        public int? TE_TotalScore { get; set; }
        [StringLength(4)]
        public string MC_FinalResult { get; set; }
        [StringLength(4)]
        public string FinalResult { get; set; }
    }
}
