// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace APATools.Models
{
    public partial class Sp_UserLoginResult
    {
        public long id { get; set; }
        [StringLength(20)]
        public string UserName { get; set; }
        public long AccessID { get; set; }
        [StringLength(50)]
        public string UserPassword { get; set; }
        public long RoleCode { get; set; }
        public string MobileNo { get; set; }
        public long LoginStatus { get; set; }
        public int CurrentLoginStatus { get; set; }
        public long ActiveStatus { get; set; }
        public long DeleteStatus { get; set; }
        public DateTime? LoginTime { get; set; }
        public DateTime? LogOutTime { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public long? StateCode { get; set; }
        public long? DistrictCode { get; set; }
        public long? SubDivisionCode { get; set; }
        public long? BlockCode { get; set; }
        public long? GPCode { get; set; }
        [StringLength(250)]
        public string StateName { get; set; }
        [StringLength(250)]
        public string DistrictName { get; set; }
        [StringLength(250)]
        public string SubDivisionName { get; set; }
        [StringLength(250)]
        public string BlockName { get; set; }
        [StringLength(250)]
        public string GPName { get; set; }
        [StringLength(10)]
        public string DistrictCodeGPMS { get; set; }
        [StringLength(10)]
        public string BlockCodeGPMS { get; set; }
    }
}
