// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APATools.Models;

[Keyless]
public partial class view_alllocation
{
    public long StateCode { get; set; }

    public long DistrictCode { get; set; }

    public long SubDivisionCode { get; set; }

    public long BlockCode { get; set; }

    public long GPCode { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string StateName { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string DistrictName { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string SubDivisionName { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string BlockName { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string GPName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DistrictCodeGPMS { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string BlockCodeGPMS { get; set; }
}